- Makefile
- Param/PARAM.in.test2.1st
- Param/PARAM.in.test2.2nd
- src/ModRamIO.f90
- src/ModRamSats.f90
Satellite output files should now be working correctly. Also added satellites to test2 in order to test the restart capability of the satellite files.
Fixes an issue introduced recently where satellite output files were not being populated, so all satellite output files were empty "templates".
> Fixed an issue with satellite output files

- src/ModRamScb.f90
Changed method of calculating element-wise sqrt to ensure that no negatives are passed to sqrt. Fixes SCB crashes in tests 3 and 4 when debug flags are enabled.
> src/ModRamScb: fix to fInt so SCB runs with debug flags set on compile

- schemeSetup.sh
Requires pspline to have either been built with NetCDF 4.6.0 (4.4.4 Fortran
wrappers) or to have been built using the NetCDF dummy module (see
pspline build instructions for details). Then simply run Config.pl with the
-uninstall option to ensure a clean setup. To build, run shcemeSetup.sh
and then make as usual.
> schemeSetup: added shell script for setup on Scheme networked resources

- src/ModRamDrift.f90
- src/ModRamRun.f90
Disabled RAM species OpenMP for testing and forgot to re-enable it. This just makes RAM work on up to 4 cores now.
> Re-enable RAM species OpenMP

- src/IM_set_parameters.f90
- src/ModRamGrids.f90
- src/ModRamIO.f90
- src/ModRamTiming.f90
Changed the 2DFlux output from a ascii file to a netcdf-4 (HDF5) file.
This cuts the size by ~75% and makes it easier for other programs to
read it in. Also added a PARAM time option instead of outputing the 
flux every hour hardcoded. 
Other file outputs from RAM and SCB should be converted to netcdf-4 
as well
> Converted 2DFlux write from ASCII to netcdf-4

- src/IM_set_parameters.f90
- src/Makefile
- src/ModRamGrids.f90
- src/ModRamIO.f90
- src/ModRamTiming.f90
- src/plane_scb.f90
RAM 2D Flux was written every hour as an ascii dump if requested. Turned it into a configurable time based write with a compressed netcdf-4 output to conserve space.
New versions of GCC would not compile the iri87 and msis86 code. Removed their calls and stopped the compiler from linking against them as they were not needed
> Change 2D flux write from ASCII dump to netcdf-4 + gcc fix

- src/ModRamMain.f90
- src/ModRamRestart.f90
- srcInterface/IM_wrapper.f90
Replaced the PathRestartOut parameter with a variable that changes when
coupled with the framework so that restart files are saved in the
same place as they are for RCM.
This change allows the Restart.pl perl script from the SWMF to handle
RAM correctly, so there is no more need to copy files from restartOUT to
restartIN.
> Updated restart saving when coupled with SWMF

- Scripts/CatLog.py
- Scripts/provisionalIndices.py
- ccmcSetup.sh
This PR provides further updates to the Python helper scripts:
- CatLog.py: for concatenating/merging log files. Finalizing Python 3 compatibility and some formatting for readability.
- provisionalIndices.py: for fetching provisional/realtime indices. Update URL for fetching F10.7 from NRCan.
It also provides a helper script for installing RAM-SCB in standalone mode for CCMC.
This script cleans the environment, loads required modules, sets variables and calls `Config.pl` to generate the Makefile includes. Then `Makefile.def` is edited to fix the C compiler flags for gcc, and finally `make` is run.
> Updates to helper scripts

- src/IM_set_parameters.f90
- src/ModRamIO.f90
- src/ModRamInit.f90
- src/ModRamParams.f90
- src/ModRamPlasmasphere.f90
- src/ModRamRun.f90
- src/ModRamScb.f90
- src/ModRamVariables.f90
- src/ModRamWPI.f90
Added a plasmasphere model that evolves the cold electron population by
using ExB transportation combined with loss and refilling terms. In
order to differentiate between using the Carpenter and Anderson model vs
the new model a new parameter was created for the PARAM file
(#PLASMASPHERE). The format is;
#PLASMASPHERE
T            DoUsePlasmasphere (T/F)
Transport    PlasmasphereModel (Carpenter/Transport)
Rasmussen    RefillingTau      (Fixed/Analytic/Rasmussen)
The RefillingTau parameter can read from a file (Fixed), can be
calculated analytically using the method in DGCPM (Analytic), or can be
calculated using the Rasmussen model (Rasmussen). Note that for all
three versions the loss time scale is currently fixed. By default the
plasmasphere is turned off.
CAVEATS:
- The new transport …
> Added a new plasmasphere model

- Makefile
- src/ModRamSats.f90
Closes #68 
- Changes the dimension of the omniflux variable in the output netCDFs to address #68 
- Fixes the Makefile so that test4 runs (it had ncdump looking for "FluxH+" which is no longer in these files)
Submitted as a draft PR as test4 is failing locally. @Pheosics - can I ask you to look into why test4 is failing here?
> Correct dimensionality of omniflux in virtual satellite files

- Makefile
- Param/PARAM.in.default
- src/IM_set_parameters.f90
- src/ModRamBoundary.f90
- src/ModRamIO.f90
- src/ModRamIndices.f90
- src/ModRamParams.f90
These changes allow the user to specify a percentage of oxygen to turn into nitrogen for a given run. This impacts the initialization by turning a given percentage from oxygen to nitrogen, and the flux at the boundary by changing the Young et al. composition percentages. The user specifies the percentage of nitrogen they want by adding 
```
#NITROGEN_PERCENT
20
```
to the PARAM file (for 20 percent oxygen to nitrogen conversion). Note that unless the user also specifies using nitrogen as a species in the PARAM file the conversion will subtract from the oxygen and the composition ratios will no longer add up to 1.
I've also set up the Makefile so that it correctly copies the NitrogenCrossSections to the input directory when making a run directory.
> Enabled nitrogen as percentage of oxygen runs

- Config.pl
- README.md
The current `Config.pl` allows for specification of the locations of both NetCDF4 and GSL, but assumes a directory structure that isn't necessarily respected on system installs. It also requires the user to explicitly know where these libraries are located and appropriate flags are hard-coded.
This PR updates this by adding the option to use `nf-config` and `gsl-config` to look up the install locations and flags.
The installation instructions in the README are also expanded.
Old behaviour is preserved.
New behaviour is that supplying `-ncdf` and `-gsl` flags without a corresponding value will then attempt to use the config utilities to look up the location and flags for each dependent library.
(Edit to note that the force-push was after rebasing against master to ensure that the PR can be …
> Auto-detect NetCDF4 and GSL locations and flags

- Config.pl
This pull request adds a version check if the supplied compiler begins with `gfortran` (compatible with `gfortran` and `gfortran-10`, as name can depend on system setup).
If the compiler name starts with `gfortran` and the version number is greater-than-or-equal-to 10, the `-fallow-argument-mismatch` and `-fallow-invalid-boz` flags get added to `Makefile.conf`.
The addition of the first flag resolves #79 and the addition of the second flag provides a temporary workaround for #78
> Fixes for GCC10

- Config.pl
- schemeSetup.sh
Compilation failed on CCMC's AWS server due to the GSL include directory not being explicitly specified for the compilation of `src\RamGSL.c`.
This PR makes `Config.pl` populate the `FLAGC_EXTRA` variable in `Makefile.conf`, so that the GSL include directory is passed as as `-I` argument to the `gcc` calls.
Can I ask @Pheosics and @kyakymenko to make sure that everything still installs fine on their systems with this PR? This works for me on Ubuntu 20.04 (on WSL2), as well as CentOS 7 (the AWS instance), and I just want to make sure it's as robust as I think it is.
> Config.pl: add GSL include dir to C compilation

- .github/workflows/ramscb-ci.yml
To run workflows, the YAML file with the actions needs to be in the upstream master branch. Once there, the actions will run on PRs so while this may fail testing due to a badly specified YAML file (bad package names, config errors, etc.) it's not possible (AFAIK) to test without doing the first merge.
So, here's a first cut at reproducing the old docker environment and test-runner that we used to use on Travis.
> Set up GitHub Actions test-runner

- .github/workflows/ramscb-ci.yml
Initial commit of the GH actions test runner fails because we're on Ubuntu 16.04 (for compatibility with the old Docker container). That means the version of Python 3 installed is too old and subsequent installation of `numpy` errors and kills the build.
This PR amends the test runner so that the setup, etc. all works and the `testTravis` test is run (same as the old TravisCI runner). Runtime on first action was 8m30s. Any additional tests should probably be run with parallel actions.
This covers part of #81, in that the CI will now be active again. However, the `gcc`/`gfortran` version is ancient and it's using Ubuntu 16.04 which will be dropped by GitHub Actions in September. So those updates (which will require updating test results) still need to be made and are fairly high priority.
> Correct build of GitHub Actions test runner

- .github/workflows/ramscb-ci.yml
- Makefile
- src/CONTRIBUTING.md
- src/Makefile
- src/ModRamFunctions.f90
- src/ModRamIndices.f90
- src/ModRamMain.f90
- src/test_suite.f90
The PR makes a number of changes to enable more fine-grained testing within RAM-SCB. Currently testing is done with a few end-to-end tests that then compare output to the previous result. The aim here is to enable specific testing *for correctness* against expected results, using shorter sections of code; i.e., this enables testing without running RAM-SCB as a simulation code.
Specific updates:
- Added some missing `use` statements that prevented compilation of external source using libRAMSCB
- Unit test program added and included in `Makefile` (build/run with `make unittest`)
- Combine static libraries for compilation, rather than unpacking to temp directory
- Short test added for `init_indices`/`update_indices` in `ModRamIndices`
- Short tests added for `erff` and `Gcoul` in …
> Add unit testing capability to RAM-SCB

- Scripts/viz/convertRAMrestart.py
- Scripts/viz/makeCustomSource.py
The visualization scripts for converting RAM-SCB restarts to VTK and for generating VTK sources for plotting use outdated idiom that's no longer supported in recent Python versions.
This changes the string equality comparison so the codes now run under modern Python.
> Fix string comparison in viz scripts

- .dockerignore
Makes sure that git history and some other target locations that may be generated in local checkouts of the repo aren't included in the context when copying the project to the Docker image.
> Reduce docker image size by including .dockerignore file

- Param/PARAM.in.RoR
- Scripts/summaryPlots.py
- launch_run.py
Fixes some issues in runs-on-request automation:
- The time range passed from the launch script to the plot script was being truncated to day boundaries leading to the last day of a run not being plotted. This is now fixed and the times are passed to minute precision.
- A timestamp annotation was added to the pressure plots (these are displayed on the RoR output webpage and file metadata is not available, so a timestamp is required)
> Plotting updates for CCMC runs-on-request
